먼저, 예제에 사용할 데이터프레임을 생성

In [3]:
import pandas as pd
import numpy as np

# 예제 데이터프레임 생성
data = {
    'City': ['Seoul', 'Seoul', 'Busan', 'Busan', 'Seoul', 'Busan', 'Seoul', 'Busan', 'Daegu', 'Daegu'],
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Keyboard', 'Mouse', 'Laptop', 'Keyboard', 'Mouse', 'Laptop', 'Keyboard'],
    'Price': [1200, 25, 1100, 75, 30, 1050, 80, 20, 950, 60],
    'Quantity': [2, 5, 3, 2, 4, 2, 3, 6, 4, 3],
    'Salesperson': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'Alice', 'Charlie', 'Bob', 'David', 'Charlie']
}
df = pd.DataFrame(data)
display(df.head())

    City   Product  Price  Quantity Salesperson
0  Seoul    Laptop   1200         2       Alice
1  Seoul     Mouse     25         5         Bob
2  Busan    Laptop   1100         3       Alice
3  Busan  Keyboard     75         2     Charlie
4  Seoul     Mouse     30         4         Bob

### `df.sort_values()`로 데이터프레임 정렬하기

특정 열(들)의 값에 따라 데이터프레임을 정렬합니다. `by` 인수에 정렬 기준이 되는 열 이름을 전달하고, `ascending` 인수를 `False`로 설정하여 내림차순으로 정렬할 수 있습니다. 여러 열로 정렬할 때는 `by` 인수에 열 이름 리스트를 전달합니다.

In [14]:
# 'Price' 열을 기준으로 오름차순 정렬
sorted_df_price = df.sort_values(by='Price')    #by:정렬기준인 컬럼or컬럼리스트
print("\n'Price' 기준으로 오름차순 정렬:")
display(sorted_df_price.head())

# 'City'와 'Price' 열을 기준으로 정렬 (City는 오름차순, Price는 내림차순)
sorted_df_multi = df.sort_values(by=['City', 'Price'], ascending=[True, False])
#ascending: True-오름차순 / False-내림차순
print("\n'City' (오름차순), 'Price' (내림차순) 기준으로 정렬:")
display(sorted_df_multi.head())

'Price' 기준으로 오름차순 정렬:

    City   Product  Price  Quantity Salesperson
7  Busan     Mouse     20         6         Bob
1  Seoul     Mouse     25         5         Bob
4  Seoul     Mouse     30         4         Bob
9  Daegu  Keyboard     60         3     Charlie
3  Busan  Keyboard     75         2     Charlie

'City' (오름차순), 'Price' (내림차순) 기준으로 정렬:

    City   Product  Price  Quantity Salesperson
2  Busan    Laptop   1100         3       Alice
5  Busan    Laptop   1050         2       Alice
3  Busan  Keyboard     75         2     Charlie
7  Busan     Mouse     20         6         Bob
8  Daegu    Laptop    950         4       David

### `df.sort_index()`로 열(Column) 정렬하기

`df.sort_index()` 메서드는 데이터프레임의 인덱스(기본값 `axis=0`) 또는 열 이름(`axis=1`)을 기준으로 정렬할 때 사용됩니다. 열 이름을 알파벳 순서로 정렬하는 예시입니다.

In [13]:
# 열 이름을 기준으로 정렬 (알파벳 순서)
sorted_columns_by_index_df = df.sort_index(axis=1)
print("\n'sort_index(axis=1)'로 열 이름이 정렬된 데이터프레임:")
display(sorted_columns_by_index_df.head())

'sort_index(axis=1)'로 열 이름이 정렬된 데이터프레임:

    City  Price   Product  Quantity Salesperson
0  Seoul   1200    Laptop         2       Alice
1  Seoul     25     Mouse         5         Bob
2  Busan   1100    Laptop         3       Alice
3  Busan     75  Keyboard         2     Charlie
4  Seoul     30     Mouse         4         Bob

### `pd.concat()`으로 데이터프레임 결합하기

두 개 이상의 데이터프레임을 행(row) 또는 열(column)을 따라 단순히 이어 붙일 때 사용합니다. df-series / df-df / series-series 가능

In [17]:
# 두 번째 데이터프레임 생성
data2 = {
    'City': ['Incheon', 'Suwon'],
    'Product': ['Monitor', 'Headset'],
    'Price': [300, 50],
    'Quantity': [1, 3],
    'Salesperson': ['Emily', 'Frank']
}
df2 = pd.DataFrame(data2)

# 행(axis=0, 기본값)을 따라 두 데이터프레임 결합
concatenated_df = pd.concat([df, df2],ignore_index=True)  #axis=0 (행)
#ignore_index=True시 기존 인덱스 무시하고 0부터 재설정
print("\n행을 따라 df와 df2 결합:")
display(concatenated_df)

# 열(axis=1)을 따라 두 데이터프레임 결합 (인덱스 기준으로 결합)
df_part1 = df[['City', 'Product']]
df_part2 = df[['Price', 'Quantity']]
concatenated_cols_df = pd.concat([df_part1, df_part2], axis=1)
#ignore_index=False (기본)
print("\n열을 따라 df_part1과 df_part2 결합:")
display(concatenated_cols_df)

행을 따라 df와 df2 결합:

       City   Product  Price  Quantity Salesperson
0     Seoul    Laptop   1200         2       Alice
1     Seoul     Mouse     25         5         Bob
2     Busan    Laptop   1100         3       Alice
3     Busan  Keyboard     75         2     Charlie
4     Seoul     Mouse     30         4         Bob
5     Busan    Laptop   1050         2       Alice
6     Seoul  Keyboard     80         3     Charlie
7     Busan     Mouse     20         6         Bob
8     Daegu    Laptop    950         4       David
9     Daegu  Keyboard     60         3     Charlie
10  Incheon   Monitor    300         1       Emily
11    Suwon   Headset     50         3       Frank

열을 따라 df_part1과 df_part2 결합:

    City   Product  Price  Quantity
0  Seoul    Laptop   1200         2
1  Seoul     Mouse     25         5
2  Busan    Laptop   1100         3
3  Busan  Keyboard     75         2
4  Seoul     Mouse     30         4
5  Busan    Laptop   1050         2
6  Seoul  Keyboard     80         3
7  Busan     Mouse     20         6
8  Daegu    Laptop    950         4
9  Daegu  Keyboard     60         3

### `df.join()`으로 데이터프레임 결합하기

`join()` 메서드는 인덱스 또는 지정된 열(key)을 기준으로 다른 데이터프레임과 결합할 때 사용됩니다. 주로 인덱스 기반으로 결합할 때 유용하며, `on` 인수를 사용하여 특정 열을 기준으로 결합할 수도 있습니다. `how` 인수로 `left`, `right`, `inner`, `outer` 조인 방식을 지정할 수 있습니다.

In [6]:
# 추가 정보 데이터프레임 생성
extra_data = {
    'City': ['Seoul', 'Busan', 'Daegu'],
    'Population': [9700000, 3400000, 2400000]
}
df_pop = pd.DataFrame(extra_data).set_index('City')

# df의 'City' 열과 df_pop의 인덱스를 기준으로 조인 (기본은 left join)
joined_df = df.join(df_pop, on='City')
#sort=False : 키값을 기준으로 정렬할지 여부
print("\n'City' 열을 기준으로 df_pop과 조인:")
display(joined_df)

# df의 인덱스를 기준으로 조인하기 위해 인덱스를 재설정
df_salesperson_info = pd.DataFrame({
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
    'Region': ['East', 'West', 'South', 'North', 'East']
}).set_index('Salesperson')

# df를 'Salesperson' 열을 인덱스로 설정 후 조인
joined_df_by_salesperson = df.set_index('Salesperson').join(df_salesperson_info, how='left')
print("\n'Salesperson' 인덱스를 기준으로 조인 (df_salesperson_info):")
display(joined_df_by_salesperson)

'City' 열을 기준으로 df_pop과 조인:

    City   Product  Price  Quantity Salesperson  Population
0  Seoul    Laptop   1200         2       Alice     9700000
1  Seoul     Mouse     25         5         Bob     9700000
2  Busan    Laptop   1100         3       Alice     3400000
3  Busan  Keyboard     75         2     Charlie     3400000
4  Seoul     Mouse     30         4         Bob     9700000
5  Busan    Laptop   1050         2       Alice     3400000
6  Seoul  Keyboard     80         3     Charlie     9700000
7  Busan     Mouse     20         6         Bob     3400000
8  Daegu    Laptop    950         4       David     2400000
9  Daegu  Keyboard     60         3     Charlie     2400000

'Salesperson' 인덱스를 기준으로 조인 (df_salesperson_info):

              City   Product  Price  Quantity Region
Salesperson
Alice        Seoul    Laptop   1200         2   East
Bob          Seoul     Mouse     25         5   West
Alice        Busan    Laptop   1100         3   East
Charlie      Busan  Keyboard     75         2  South
Bob          Seoul     Mouse     30         4   West
Alice        Busan    Laptop   1050         2   East
Charlie      Seoul  Keyboard     80         3  South
Bob          Busan     Mouse     20         6   West
David        Daegu    Laptop    950         4  North
Charlie      Daegu  Keyboard     60         3  South

### `df.merge()`로 데이터프레임 결합하기

`merge()`는 SQL의 JOIN과 유사하게 하나 또는 여러 개의 키 열을 기반으로 두 데이터프레임을 결합하는 가장 강력하고 유연한 방법입니다. `on`, `left_on`, `right_on` 인수를 사용하여 결합 키를 지정하고, `how` 인수로 `inner` (기본값), `left`, `right`, `outer` 조인 방식을 선택할 수 있습니다.

`pd.merge(df1, df2, ...)`와 같은 **함수형 방식**과 `df1.merge(df2, ...)`와 같은 **메서드형 방식**으로 모두 사용할 수 있습니다.

In [18]:
# 도시별 지역 정보를 포함하는 데이터프레임 생성
city_region = pd.DataFrame({
    'City': ['Seoul', 'Busan', 'Daegu', 'Incheon'],
    'Region': ['Capital', 'SouthEast', 'SouthEast', 'Capital']
})

# 'City' 열을 기준으로 두 데이터프레임 병합 (함수형: inner merge)
merged_df_func = pd.merge(df, city_region, on='City', how='inner')
print("\n'City' 열을 기준으로 함수형 inner merge:")
display(merged_df_func)

# 'City' 열을 기준으로 두 데이터프레임 병합 (메서드형: left merge)
# df에 city_region을 merge
merged_df_method = df.merge(city_region, on='City', how='left')
print("\n'City' 열을 기준으로 메서드형 left merge:")
display(merged_df_method)


# 제품별 카테고리 정보를 포함하는 데이터프레임 생성
product_category = pd.DataFrame({
    'Item': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headset'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories']
})

# 'Product' 열과 'Item' 열을 기준으로 left merge
merged_df_left = pd.merge(df, product_category, left_on='Product', right_on='Item', how='left')
print("\n'Product' (df)와 'Item' (product_category)을 기준으로 left merge (함수형):")
display(merged_df_left)

'City' 열을 기준으로 함수형 inner merge:

    City   Product  Price  Quantity Salesperson     Region
0  Seoul    Laptop   1200         2       Alice    Capital
1  Seoul     Mouse     25         5         Bob    Capital
2  Busan    Laptop   1100         3       Alice  SouthEast
3  Busan  Keyboard     75         2     Charlie  SouthEast
4  Seoul     Mouse     30         4         Bob    Capital
5  Busan    Laptop   1050         2       Alice  SouthEast
6  Seoul  Keyboard     80         3     Charlie    Capital
7  Busan     Mouse     20         6         Bob  SouthEast
8  Daegu    Laptop    950         4       David  SouthEast
9  Daegu  Keyboard     60         3     Charlie  SouthEast

'City' 열을 기준으로 메서드형 left merge:

    City   Product  Price  Quantity Salesperson     Region
0  Seoul    Laptop   1200         2       Alice    Capital
1  Seoul     Mouse     25         5         Bob    Capital
2  Busan    Laptop   1100         3       Alice  SouthEast
3  Busan  Keyboard     75         2     Charlie  SouthEast
4  Seoul     Mouse     30         4         Bob    Capital
5  Busan    Laptop   1050         2       Alice  SouthEast
6  Seoul  Keyboard     80         3     Charlie    Capital
7  Busan     Mouse     20         6         Bob  SouthEast
8  Daegu    Laptop    950         4       David  SouthEast
9  Daegu  Keyboard     60         3     Charlie  SouthEast

'Product' (df)와 'Item' (product_category)을 기준으로 left merge (함수형):

    City   Product  Price  Quantity Salesperson      Item     Category
0  Seoul    Laptop   1200         2       Alice    Laptop  Electronics
1  Seoul     Mouse     25         5         Bob     Mouse  Electronics
2  Busan    Laptop   1100         3       Alice    Laptop  Electronics
3  Busan  Keyboard     75         2     Charlie  Keyboard  Electronics
4  Seoul     Mouse     30         4         Bob     Mouse  Electronics
5  Busan    Laptop   1050         2       Alice    Laptop  Electronics
6  Seoul  Keyboard     80         3     Charlie  Keyboard  Electronics
7  Busan     Mouse     20         6         Bob     Mouse  Electronics
8  Daegu    Laptop    950         4       David    Laptop  Electronics
9  Daegu  Keyboard     60         3     Charlie  Keyboard  Electronics

### `df.groupby()`로 데이터프레임 요약하기

`groupby()` 메서드는 특정 기준(하나 이상의 열)으로 데이터를 그룹화하고, 각 그룹에 대해 집계 함수(예: `sum()`, `mean()`, `count()`, `min()`, `max()`)를 적용하여 데이터를 요약합니다.
집계함수들 'std()', 'var()', 'quantile(n)', 'median()', 'describe()'

In [21]:
# 'City'별 'Price'의 평균 계산
avg_price_by_city = df.groupby('City')['Price'].mean()
print("\n'City'별 'Price' 평균:")
display(avg_price_by_city)

# 'City'와 'Product'별 'Quantity'의 합계 계산
total_quantity_by_city_product = df.groupby(['City', 'Product'])['Quantity'].sum()
print("\n'City'와 'Product'별 'Quantity' 합계:")
display(total_quantity_by_city_product)
#as_index=True :그룹 레이블이 인덱스로 출력될지 여부


# 여러 집계 함수를 동시에 적용
aggregated_df = df.groupby('Salesperson').agg(
    Total_Sales=('Price', 'sum'),
    Average_Quantity=('Quantity', 'mean'),
    Num_Transactions=('City', 'count')
)   #여러 함수를동시에 쓰면서 컬럼명명 변경
print("\n'Salesperson'별 다중 집계:")
display(aggregated_df)

'City'별 'Price' 평균:

City
Busan    561.25
Daegu    505.00
Seoul    333.75
Name: Price, dtype: float64

'City'와 'Product'별 'Quantity' 합계:

City   Product
Busan  Keyboard    2
       Laptop      5
       Mouse       6
Daegu  Keyboard    3
       Laptop      4
Seoul  Keyboard    3
       Laptop      2
       Mouse       9
Name: Quantity, dtype: int64

'Salesperson'별 다중 집계:

             Total_Sales  Average_Quantity  Num_Transactions
Salesperson
Alice               3350          2.333333                 3
Bob                   75          5.000000                 3
Charlie              215          2.666667                 3
David                950          4.000000                 1

### `pd.Series.value_counts()`로 도수분포표 만들기

`value_counts()` 메서드는 Series(데이터프레임의 단일 열)의 고유한 값들의 빈도(개수)를 계산하여 도수분포표를 반환합니다. 결과는 내림차순으로 정렬된 Series 형태입니다.

In [22]:
# 'City' 열의 도수분포표 생성
city_counts = df['City'].value_counts()
print("\n'City' 열의 도수분포표:")
display(city_counts)

# 정규화된 빈도 (비율) 계산
product_proportions = df['Product'].value_counts(normalize=True)
print("\n'Product' 열의 정규화된 도수분포표 (비율):")
display(product_proportions)

'City' 열의 도수분포표:

City
Seoul    4
Busan    4
Daegu    2
Name: count, dtype: int64

'Product' 열의 도수분포표:

Product
Laptop      4
Mouse       3
Keyboard    3
Name: count, dtype: int64

'Product' 열의 정규화된 도수분포표 (비율):

Product
Laptop      0.4
Mouse       0.3
Keyboard    0.3
Name: proportion, dtype: float64

### `pd.crosstab()`으로 교차표(Cross-tabulation) 만들기

`pd.crosstab()` 함수는 두 개 이상의 요인(factor)에 대한 교차 빈도를 계산하여 테이블 형태로 보여줍니다. 주로 범주형 변수 간의 관계를 분석할 때 사용됩니다.

In [10]:
# 'City'와 'Product' 간의 교차표 생성
crosstab_city_product = pd.crosstab(df['City'], df['Product'])
print("\n'City'와 'Product' 간의 교차표:")
display(crosstab_city_product)
#dropna=True : 항목이 모두 nan인 열 제외
#pd.crosstab(index, columns)

# 'City'와 'Salesperson' 간의 교차표 생성 (마진 합계 포함)
crosstab_city_salesperson = pd.crosstab(df['City'], df['Salesperson'], margins=True)
print("\n'City'와 'Salesperson' 간의 교차표 (margins=True):")
display(crosstab_city_salesperson)

# 교차표에 집계 함수 적용 (예: 평균 가격)
crosstab_agg_price = pd.crosstab(
    df['City'],
    df['Product'],
    values=df['Price'],
    aggfunc='mean'
)
print("\n'City'와 'Product'별 평균 가격 교차표:")
display(crosstab_agg_price)

'City'와 'Product' 간의 교차표:

Product  Keyboard  Laptop  Mouse
City
Busan           1       2      1
Daegu           1       1      0
Seoul           1       1      2

'City'와 'Salesperson' 간의 교차표 (margins=True):

Salesperson  Alice  Bob  Charlie  David  All
City
Busan            2    1        1      0    4
Daegu            0    0        1      1    2
Seoul            1    2        1      0    4
All              3    3        3      1   10

'City'와 'Product'별 평균 가격 교차표:

Product  Keyboard  Laptop  Mouse
City
Busan        75.0  1075.0   20.0
Daegu        60.0   950.0    NaN
Seoul        80.0  1200.0   27.5