#####조건에 맞는 데이터 탐색 및 수정

In [ ]:
import pandas as pd
import numpy as np

# 예제 DataFrame 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, 30, 35, 40, 28, 32, 45, 29],
    'City': ['Seoul', 'Busan', 'Seoul', 'Jeju', 'Busan', 'Seoul', 'Jeju', 'Busan'],
    'Salary': [50000, 55000, 60000, 70000, 52000, 58000, 75000, 53000],
    'Status': ['Single', 'Married', 'Single', 'Married', 'Single', 'Single', 'Married', 'Married']
}
df = pd.DataFrame(data)

print("원본 DataFrame:")
df.head()

원본 DataFrame:

      Name  Age   City  Salary   Status
0    Alice   25  Seoul   50000   Single
1      Bob   30  Busan   55000  Married
2  Charlie   35  Seoul   60000   Single
3    David   40   Jeju   70000  Married
4      Eve   28  Busan   52000   Single

### 1. 조건에 따른 행 선택 (데이터 탐색)

In [ ]:
# 1.1. 'Age'가 30보다 큰 사람 선택
print("Age > 30 인 사람:")
display(df[df['Age'] > 30])

# 1.2. 'City'가 'Seoul'인 사람 선택
print("City가 Seoul 인 사람:")
display(df[df['City'] == 'Seoul'])

Age > 30 인 사람:

      Name  Age   City  Salary   Status
2  Charlie   35  Seoul   60000   Single
3    David   40   Jeju   70000  Married
5    Frank   32  Seoul   58000   Single
6    Grace   45   Jeju   75000  Married

City가 Seoul 인 사람:

      Name  Age   City  Salary  Status
0    Alice   25  Seoul   50000  Single
2  Charlie   35  Seoul   60000  Single
5    Frank   32  Seoul   58000  Single

In [ ]:
# 1.3. 여러 조건에 따른 행 선택 (AND 조건: & 사용)
# 'Age'가 30보다 크고 'City'가 'Busan'인 사람
print("Age > 30 이고 City가 Busan 인 사람:")
display(df[(df['Age'] > 30) & (df['City'] == 'Busan')])

# 1.4. 여러 조건에 따른 행 선택 (OR 조건: | 사용)
# 'Age'가 40보다 크거나 'City'가 'Seoul'인 사람
print("Age > 40 이거나 City가 Seoul 인 사람:")
display(df[(df['Age'] > 40) | (df['City'] == 'Seoul')])

Age > 30 이고 City가 Busan 인 사람:

Empty DataFrame
Columns: [Name, Age, City, Salary, Status]
Index: []

Age > 40 이거나 City가 Seoul 인 사람:

      Name  Age   City  Salary   Status
0    Alice   25  Seoul   50000   Single
2  Charlie   35  Seoul   60000   Single
5    Frank   32  Seoul   58000   Single
6    Grace   45   Jeju   75000  Married

### 2. 조건에 따른 데이터 수정

In [ ]:
# 2.1. 'Age'가 35 이상인 사람들의 'Salary'를 10% 인상
# .loc[] 를 사용하여 조건에 맞는 행과 열을 선택하여 값을 수정합니다.
df.loc[df['Age'] >= 35, 'Salary'] = df.loc[df['Age'] >= 35, 'Salary'] * 1.1

print("Age가 35 이상인 사람들의 Salary 10% 인상 후:")
df.head()

Age가 35 이상인 사람들의 Salary 10% 인상 후:

      Name  Age   City  Salary   Status
0    Alice   25  Seoul   50000   Single
1      Bob   30  Busan   55000  Married
2  Charlie   35  Seoul   66000   Single
3    David   40   Jeju   77000  Married
4      Eve   28  Busan   52000   Single

In [ ]:
# 2.2. 'Status'가 'Married'이고 'City'가 'Jeju'인 사람들의 'Status'를 'Married (Jeju)'로 변경
df.loc[(df['Status'] == 'Married') & (df['City'] == 'Jeju'), 'Status'] = 'Married (Jeju)'

print("조건에 따른 Status 변경 후:")
df.head()

조건에 따른 Status 변경 후:

      Name  Age   City  Salary          Status
0    Alice   25  Seoul   50000          Single
1      Bob   30  Busan   55000         Married
2  Charlie   35  Seoul   66000          Single
3    David   40   Jeju   77000  Married (Jeju)
4      Eve   28  Busan   52000          Single

### 3. 조건에 따른 새로운 열 추가

In [ ]:
# 3.1. 'Age'가 30 이상이면 'Senior', 아니면 'Junior'인 'Level' 열 추가
# numpy의 where 함수를 사용하면 편리합니다.
df['Level'] = np.where(df['Age'] >= 30, 'Senior', 'Junior')

# 3.2. 'Salary'가 60000 이상이면 'High', 아니면 'Normal'인 'Salary_Tier' 열 추가
df['Salary_Tier'] = np.where(df['Salary'] >= 60000, 'High', 'Normal')

print("새로운 열 추가 후 DataFrame:")
df.head()

새로운 열 추가 후 DataFrame:

      Name  Age   City  Salary          Status   Level Salary_Tier
0    Alice   25  Seoul   50000          Single  Junior      Normal
1      Bob   30  Busan   55000         Married  Senior      Normal
2  Charlie   35  Seoul   66000          Single  Senior        High
3    David   40   Jeju   77000  Married (Jeju)  Senior        High
4      Eve   28  Busan   52000          Single  Junior      Normal

In [ ]:
# 3.0. 조건에 따라 'Is_High_Earner' 컬럼 추가 (Salary가 60000 이상이면 True, 아니면 False)
# .loc[]를 사용하여 조건에 맞는 새로운 컬럼을 할당할 수 있습니다.
df.loc[df['Salary'] >= 60000, 'Is_High_Earner'] = True
df.loc[df['Salary'] < 60000, 'Is_High_Earner'] = False

print("새로운 'Is_High_Earner' 열 추가 후 DataFrame:")
df.head()

새로운 'Is_High_Earner' 열 추가 후 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner
0,Alice,25,Seoul,50000,Single,Junior,Normal,False
1,Bob,30,Busan,55000,Married,Senior,Normal,False
2,Charlie,35,Seoul,66000,Single,Senior,High,True
3,David,40,Jeju,77000,Married (Jeju),Senior,High,True
4,Eve,28,Busan,52000,Single,Junior,Normal,False

In [ ]:
# 3.3. 'Age'와 'Salary'를 기준으로 'Category' 열 추가 (np.select 사용)
# np.select는 여러 조건과 그에 따른 값을 할당할 때 유용합니다.
conditions = [
    (df['Age'] >= 40),
    (df['Age'] >= 30) & (df['Salary'] >= 60000),
    (df['Age'] < 30)
]
choices = ['High-Age', 'Mid-Age High-Salary', 'Young']
df['Category'] = np.select(conditions, choices, default='Other')

print("np.select를 사용하여 'Category' 열 추가 후 DataFrame:")
df.head()

np.select를 사용하여 'Category' 열 추가 후 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25,Seoul,50000,Single,Junior,Normal,False,Young
1,Bob,30,Busan,55000,Married,Senior,Normal,False,Other
2,Charlie,35,Seoul,66000,Single,Senior,High,True,Mid-Age High-Salary
3,David,40,Jeju,77000,Married (Jeju),Senior,High,True,High-Age
4,Eve,28,Busan,52000,Single,Junior,Normal,False,Young

### 4. 결측값 탐색 및 수정

In [ ]:
# 결측값 처리를 위한 예제 DataFrame 생성 (원본 df의 복사본에 결측값 추가)
df_missing = df.copy()

df_missing.loc[2, 'Age'] = np.nan  # Charlie의 Age에 결측값 추가
df_missing.loc[5, 'Salary'] = np.nan # Frank의 Salary에 결측값 추가
df_missing.loc[0, 'City'] = np.nan # Alice의 City에 결측값 추가
df_missing.loc[7, 'Status'] = np.nan # Heidi의 Status에 결측값 추가

print("결측값이 포함된 DataFrame:")
display(df_missing)

결측값이 포함된 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.0,NaN,50000.0,Single,Junior,Normal,False,Young
1,Bob,30.0,Busan,55000.0,Married,Senior,Normal,False,Other
2,Charlie,NaN,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
3,David,40.0,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.0,Busan,52000.0,Single,Junior,Normal,False,Young
5,Frank,32.0,Seoul,NaN,Single,Senior,Normal,False,Other
6,Grace,45.0,Jeju,82500.0,Married (Jeju),Senior,High,True,High-Age
7,Heidi,29.0,Busan,53000.0,NaN,Junior,Normal,False,Young

In [ ]:
# 4.1. 결측값 탐색 (컬럼별 결측값 개수 확인)
print("컬럼별 결측값 개수:")
display(df_missing.isnull().sum())

# 결측값이 있는 행 확인
print("결측값이 있는 행:")
display(df_missing[df_missing.isnull().any(axis=1)])

컬럼별 결측값 개수:

Name              0
Age               1
City              1
Salary            1
Status            1
Level             0
Salary_Tier       0
Is_High_Earner    0
Category          0
dtype: int64

결측값이 있는 행:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.0,NaN,50000.0,Single,Junior,Normal,False,Young
2,Charlie,NaN,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
5,Frank,32.0,Seoul,NaN,Single,Senior,Normal,False,Other
7,Heidi,29.0,Busan,53000.0,NaN,Junior,Normal,False,Young

In [ ]:
# 4.1.1. 'isna()'를 사용한 결측값 탐색 (컬럼별 결측값 개수 확인)
print("컬럼별 결측값 개수 (isna() 사용):")
display(df_missing.isna().sum())

# 'isna()'를 사용하여 결측값이 있는 행 확인
print("결측값이 있는 행 (isna() 사용):")
display(df_missing[df_missing.isna().any(axis=1)])

컬럼별 결측값 개수 (isna() 사용):

Name              0
Age               1
City              1
Salary            1
Status            1
Level             0
Salary_Tier       0
Is_High_Earner    0
Category          0
dtype: int64

결측값이 있는 행 (isna() 사용):

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.0,NaN,50000.0,Single,Junior,Normal,False,Young
2,Charlie,NaN,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
5,Frank,32.0,Seoul,NaN,Single,Senior,Normal,False,Other
7,Heidi,29.0,Busan,53000.0,NaN,Junior,Normal,False,Young

In [ ]:
# 4.1.2. 'isna()'를 사용하여 DataFrame 전체의 결측 여부 확인
print("DataFrame 전체의 결측 여부 (isna() 사용):")
display(df_missing.isna().head())

# 4.1.3. 'notna()'를 사용하여 DataFrame 전체의 비결측 여부 확인
print("DataFrame 전체의 비결측 여부 (notna() 사용):")
display(df_missing.notna().head())

DataFrame 전체의 결측 여부 (isna() 사용):

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

DataFrame 전체의 비결측 여부 (notna() 사용):

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,True,True,False,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,False,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True

In [ ]:
# 4.2. 숫자형 결측값 채우기 (평균값, 중앙값, 특정 값 등)
# fillna(method='ffill') (pad) 또는 fillna(method='bfill') (backfill) 같은 메서드를 사용하여 앞/뒤 값으로 채울 수도 있습니다.
# 'Age' 컬럼의 결측값을 평균으로 채우기
df_missing['Age'] = df_missing['Age'].fillna(df_missing['Age'].mean())

# 'Salary' 컬럼의 결측값을 0으로 채우기
df_missing['Salary'] = df_missing['Salary'].fillna(0)

print("숫자형 결측값 처리 후 DataFrame (Age는 평균, Salary는 0으로 채움):")
df_missing.head()

숫자형 결측값 처리 후 DataFrame (Age는 평균, Salary는 0으로 채움):

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.000000,Busan,50000.0,Single,Junior,Normal,False,Young
1,Bob,30.000000,Busan,55000.0,Married,Senior,Normal,False,Other
2,Charlie,32.714286,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
3,David,40.000000,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.000000,Busan,52000.0,Single,Junior,Normal,False,Young

### 5. 중복값 탐색 및 제거 (`drop_duplicates()`)

In [ ]:
# 중복값 처리를 위한 예제 DataFrame 생성
data_dup = {
    'ID': [1, 2, 3, 1, 4, 5, 2, 6],
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Eve', 'Bob', 'Frank'],
    'City': ['Seoul', 'Busan', 'Seoul', 'Seoul', 'Jeju', 'Busan', 'Busan', 'Seoul'],
    'Score': [85, 90, 78, 85, 92, 88, 90, 75]
}
df_dup = pd.DataFrame(data_dup)

print("중복값이 포함된 원본 DataFrame:")
display(df_dup.head())

중복값이 포함된 원본 DataFrame:

   ID     Name   City  Score
0   1    Alice  Seoul     85
1   2      Bob  Busan     90
2   3  Charlie  Seoul     78
3   1    Alice  Seoul     85
4   4    David   Jeju     92

In [ ]:
# 5.1. 특정 키 컬럼의 고유값 확인 (set() 예제는 주석으로)
print("\n'ID' 컬럼의 고유값 (drop_duplicates() 사용):")
display(df_dup['ID'].drop_duplicates())

# print("\n'ID' 컬럼의 고유값 (set() 사용):")
# display(set(df_dup['ID']))

'ID' 컬럼의 고유값 (drop_duplicates() 사용):

0    1
1    2
2    3
4    4
5    5
7    6
Name: ID, dtype: int64

In [ ]:
# 4.4. 결측값이 있는 행 또는 열 제거
# (위에서 fillna를 사용했으므로, 다시 결측값을 만들어 예제를 진행합니다)

df_dropna_example = df.copy()
df_dropna_example.loc[2, 'Age'] = np.nan # 결측값 추가
df_dropna_example.loc[5, 'Salary'] = np.nan # 결측값 추가
df_dropna_example.loc[0, 'City'] = np.nan # 결측값 추가

print("원본에서 결측값을 다시 추가한 DataFrame:")
display(df_dropna_example.head())

# 결측값이 있는 모든 행 제거
df_dropped_rows = df_dropna_example.dropna(axis=0)
print("결측값이 있는 행 제거 후 DataFrame:")
display(df_dropped_rows.head())

# 결측값이 있는 모든 열 제거 (이 예제에서는 열을 제거할 필요가 없을 수 있음)
# df_dropped_columns = df_dropna_example.dropna(axis=1)
# print("결측값이 있는 열 제거 후 DataFrame:")
# display(df_dropped_columns)

# 5.2. 중복된 행 제거
# DataFrame 전체에서 모든 컬럼 값이 동일한 행을 제거합니다.
# subset 인자를 사용하여 특정 컬럼을 기준으로 중복을 판단할 수도 있습니다.
df_no_duplicates = df_dup.drop_duplicates()
print("\n중복 행 제거 후 DataFrame:")
display(df_no_duplicates)

# 'Name' 컬럼을 기준으로 중복 제거 (첫 번째 값 유지)
# subset: 중복을 판단할 컬럼을 지정합니다. 여기에 지정된 컬럼들의 조합이 중복되는 경우에만 중복으로 간주합니다.
# keep: 'first' (기본값)는 첫 번째 중복을 유지하고 나머지를 제거합니다. 'last'는 마지막 중복을 유지하고 나머지를 제거하며, False는 모든 중복을 제거합니다.
df_no_duplicates_name = df_dup.drop_duplicates(subset=['Name'], keep='first')
print("\n'Name' 컬럼을 기준으로 중복 행 제거 (첫 번째 값 유지) 후 DataFrame:")
display(df_no_duplicates_name)

# 'Name'과 'City' 컬럼을 기준으로 중복 제거 (마지막 값 유지)
df_no_duplicates_name_city_last = df_dup.drop_duplicates(subset=['Name', 'City'], keep='last')
print("\n'Name'과 'City' 컬럼을 기준으로 중복 행 제거 (마지막 값 유지) 후 DataFrame:")
display(df_no_duplicates_name_city_last)

원본에서 결측값을 다시 추가한 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.0,NaN,50000.0,Single,Junior,Normal,False,Young
1,Bob,30.0,Busan,55000.0,Married,Senior,Normal,False,Other
2,Charlie,NaN,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
3,David,40.0,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.0,Busan,52000.0,Single,Junior,Normal,False,Young

결측값이 있는 행 제거 후 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
1,Bob,30.0,Busan,55000.0,Married,Senior,Normal,False,Other
3,David,40.0,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.0,Busan,52000.0,Single,Junior,Normal,False,Young
6,Grace,45.0,Jeju,82500.0,Married (Jeju),Senior,High,True,High-Age
7,Heidi,29.0,Busan,53000.0,Married,Junior,Normal,False,Young

중복 행 제거 후 DataFrame:

   ID     Name   City  Score
0   1    Alice  Seoul     85
1   2      Bob  Busan     90
2   3  Charlie  Seoul     78
4   4    David   Jeju     92
5   5      Eve  Busan     88
7   6    Frank  Seoul     75

'Name' 컬럼을 기준으로 중복 행 제거 후 DataFrame:

   ID     Name   City  Score
0   1    Alice  Seoul     85
1   2      Bob  Busan     90
2   3  Charlie  Seoul     78
4   4    David   Jeju     92
5   5      Eve  Busan     88
7   6    Frank  Seoul     75

'Name'과 'City' 컬럼을 기준으로 중복 행 제거 (마지막 값 유지) 후 DataFrame:

   ID     Name   City  Score
2   3  Charlie  Seoul     78
3   1    Alice  Seoul     85
4   4    David   Jeju     92
5   5      Eve  Busan     88
6   2      Bob  Busan     90
7   6    Frank  Seoul     75

In [ ]:
# 4.3. 범주형 결측값 채우기 (최빈값 또는 'Unknown' 등으로)
# fillna(method='ffill') (pad) 또는 fillna(method='bfill') (backfill) 같은 메서드를 사용하여 앞/뒤 값으로 채울 수도 있습니다.
# 'City' 컬럼의 결측값을 최빈값으로 채우기
most_frequent_city = df_missing['City'].mode()[0]   #mode는 최빈값 나타내는 함수
                                                    #최빈값이 두 개일 수 있어서 [0]을 사용
                                                    #mode리턴값을 시리즈임
df_missing['City'] = df_missing['City'].fillna(most_frequent_city)

# 'Status' 컬럼의 결측값을 'Unknown'으로 채우기
df_missing['Status'] = df_missing['Status'].fillna('Unknown')

print("범주형 결측값 처리 후 DataFrame (City는 최빈값, Status는 'Unknown'으로 채움):")
df_missing.head()

범주형 결측값 처리 후 DataFrame (City는 최빈값, Status는 'Unknown'으로 채움):

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.000000,Busan,50000.0,Single,Junior,Normal,False,Young
1,Bob,30.000000,Busan,55000.0,Married,Senior,Normal,False,Other
2,Charlie,32.714286,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
3,David,40.000000,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.000000,Busan,52000.0,Single,Junior,Normal,False,Young

In [ ]:
# 4.4. 결측값이 있는 행 또는 열 제거
# (위에서 fillna를 사용했으므로, 다시 결측값을 만들어 예제를 진행합니다)

df_dropna_example = df.copy()
df_dropna_example.loc[2, 'Age'] = np.nan # 결측값 추가
df_dropna_example.loc[5, 'Salary'] = np.nan # 결측값 추가
df_dropna_example.loc[0, 'City'] = np.nan # 결측값 추가

print("원본에서 결측값을 다시 추가한 DataFrame:")
display(df_dropna_example.head())

# 결측값이 있는 모든 행 제거
df_dropped_rows = df_dropna_example.dropna(axis=0)
print("결측값이 있는 행 제거 후 DataFrame:")
display(df_dropped_rows.head())

# 결측값이 있는 모든 열 제거 (이 예제에서는 열을 제거할 필요가 없을 수 있음)
# df_dropped_columns = df_dropna_example.dropna(axis=1)
# print("결측값이 있는 열 제거 후 DataFrame:")
# display(df_dropped_columns)

원본에서 결측값을 다시 추가한 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
0,Alice,25.0,NaN,50000.0,Single,Junior,Normal,False,Young
1,Bob,30.0,Busan,55000.0,Married,Senior,Normal,False,Other
2,Charlie,NaN,Seoul,66000.0,Single,Senior,High,True,Mid-Age High-Salary
3,David,40.0,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.0,Busan,52000.0,Single,Junior,Normal,False,Young

결측값이 있는 행 제거 후 DataFrame:

,Name,Age,City,Salary,Status,Level,Salary_Tier,Is_High_Earner,Category
1,Bob,30.0,Busan,55000.0,Married,Senior,Normal,False,Other
3,David,40.0,Jeju,77000.0,Married (Jeju),Senior,High,True,High-Age
4,Eve,28.0,Busan,52000.0,Single,Junior,Normal,False,Young
6,Grace,45.0,Jeju,82500.0,Married (Jeju),Senior,High,True,High-Age
7,Heidi,29.0,Busan,53000.0,Married,Junior,Normal,False,Young