### 1. 데이터 재구조화 (Data Restructuring)

In [ ]:
print("원본 DataFrame:")
display(df)

# df.pivot_table
print("\n1-1. `df.pivot_table` 예시 (Region별 Category의 Sales_Q1 합계):")
pivoted_df = df.pivot_table(values='Sales_Q1', index='Region', columns='Category', aggfunc='sum', fill_value=0)
display(pivoted_df)

# df.melt
print("\n1-2. `df.melt` 예시 (Sales_Q1, Sales_Q2 컬럼을 행으로 변환):")
melted_df = df.melt(id_vars=['Date', 'Category', 'Product'], value_vars=['Sales_Q1', 'Sales_Q2'], var_name='Quarter', value_name='Sales')
display(melted_df)

원본 DataFrame:

,Date,Category,Product,Region,Sales_Q1,Sales_Q2,Description,Email
0,2023-01-01,A,Apple,East,100,110,"Fresh, Red",user1@example.com
1,2023-01-01,B,Banana,West,150,160,"Sweet, Yellow",user2@gmail.com
2,2023-01-02,A,Apple,East,120,130,"Organic, Green",admin@example.com
3,2023-01-02,C,Orange,North,80,90,"Citrus, Juicy",guest@outlook.com
4,2023-01-03,B,Banana,South,200,210,"Ripe, Soft",support@gmail.com

1-1. `df.pivot_table` 예시 (Region별 Category의 Sales_Q1 합계):

Category    A    B   C
Region
East      220    0   0
North       0    0  80
South       0  200   0
West        0  150   0

1-2. `df.melt` 예시 (Sales_Q1, Sales_Q2 컬럼을 행으로 변환):

        Date Category Product   Quarter  Sales
0 2023-01-01        A   Apple  Sales_Q1    100
1 2023-01-01        B  Banana  Sales_Q1    150
2 2023-01-02        A   Apple  Sales_Q1    120
3 2023-01-02        C  Orange  Sales_Q1     80
4 2023-01-03        B  Banana  Sales_Q1    200
5 2023-01-01        A   Apple  Sales_Q2    110
6 2023-01-01        B  Banana  Sales_Q2    160
7 2023-01-02        A   Apple  Sales_Q2    130
8 2023-01-02        C  Orange  Sales_Q2     90
9 2023-01-03        B  Banana  Sales_Q2    210

### 2. DataFrame에 함수 적용 (Applying Functions to DataFrame)

In [ ]:
# apply (컬럼에 함수 적용 - Sales_Q1과 Sales_Q2의 합계 계산)
print("2-1. `apply` 예시 (두 Sales 컬럼의 합계):")
df['Total_Sales'] = df[['Sales_Q1', 'Sales_Q2']].apply(lambda x: x.sum(), axis=1)
display(df)

# map (Category 컬럼 값 매핑)
print("\n2-2. `map` 예시 (Category 약어를 전체 이름으로 매핑):")
category_map = {'A': 'Fruit', 'B': 'Fruit', 'C': 'Vegetable'}
df['Category_Full'] = df['Category'].map(category_map)
display(df)

2-1. `apply` 예시 (두 Sales 컬럼의 합계):

,Date,Category,Product,Region,Sales_Q1,Sales_Q2,Description,Email,Total_Sales
0,2023-01-01,A,Apple,East,100,110,"Fresh, Red",user1@example.com,210
1,2023-01-01,B,Banana,West,150,160,"Sweet, Yellow",user2@gmail.com,310
2,2023-01-02,A,Apple,East,120,130,"Organic, Green",admin@example.com,250
3,2023-01-02,C,Orange,North,80,90,"Citrus, Juicy",guest@outlook.com,170
4,2023-01-03,B,Banana,South,200,210,"Ripe, Soft",support@gmail.com,410

2-2. `map` 예시 (Category 약어를 전체 이름으로 매핑):

,Date,Category,Product,Region,Sales_Q1,Sales_Q2,Description,Email,Total_Sales,Category_Full
0,2023-01-01,A,Apple,East,100,110,"Fresh, Red",user1@example.com,210,Fruit
1,2023-01-01,B,Banana,West,150,160,"Sweet, Yellow",user2@gmail.com,310,Fruit
2,2023-01-02,A,Apple,East,120,130,"Organic, Green",admin@example.com,250,Fruit
3,2023-01-02,C,Orange,North,80,90,"Citrus, Juicy",guest@outlook.com,170,Vegetable
4,2023-01-03,B,Banana,South,200,210,"Ripe, Soft",support@gmail.com,410,Fruit

### 3. 문자열 데이터 변환 (String Data Transformation)

In [ ]:
print("원본 Product 컬럼:")
display(df['Product'])

# df.str.upper
print("\n3-1. `df.str.upper` 예시:")
df['Product_Upper'] = df['Product'].str.upper()
display(df['Product_Upper'])

# df.str.lower
print("\n3-2. `df.str.lower` 예시:")
df['Product_Lower'] = df['Product'].str.lower()
display(df['Product_Lower'])

# df.str.capitalize
print("\n3-3. `df.str.capitalize` 예시 (첫 글자만 대문자, 나머지는 소문자):")
df['Product_Capitalize'] = df['Product'].str.capitalize()
display(df['Product_Capitalize'])

# df.str.title
print("\n3-4. `df.str.title` 예시 (각 단어의 첫 글자 대문자):")
df['Product_Title'] = df['Product'].str.title()
display(df['Product_Title'])

원본 Product 컬럼:

0     Apple
1    Banana
2     Apple
3    Orange
4    Banana
Name: Product, dtype: object

3-1. `df.str.upper` 예시:

0     APPLE
1    BANANA
2     APPLE
3    ORANGE
4    BANANA
Name: Product_Upper, dtype: object

3-2. `df.str.lower` 예시:

0     apple
1    banana
2     apple
3    orange
4    banana
Name: Product_Lower, dtype: object

3-3. `df.str.capitalize` 예시 (첫 글자만 대문자, 나머지는 소문자):

0     Apple
1    Banana
2     Apple
3    Orange
4    Banana
Name: Product_Capitalize, dtype: object

3-4. `df.str.title` 예시 (각 단어의 첫 글자 대문자):

0     Apple
1    Banana
2     Apple
3    Orange
4    Banana
Name: Product_Title, dtype: object

### 4. 문자열 분리, 가져오기, 치환 (String Split, Get, Replace)

In [ ]:
print("원본 Description 컬럼:")
display(df['Description'])

# str.split
print("\n4-1. `str.split` 예시 (콤마로 Description 분리):")
df[['Desc_Part1', 'Desc_Part2']] = df['Description'].str.split(', ', expand=True)
display(df[['Desc_Part1', 'Desc_Part2']])

# str.get (분리된 문자열의 특정 인덱스 가져오기)
print("\n4-2. `str.get` 예시 (Description의 첫 번째 분리된 부분):")
df['Desc_First_Part'] = df['Description'].str.split(', ').str.get(0)
display(df['Desc_First_Part'])

# str.replace()
print("\n4-3. `str.replace()` 예시 (Description에서 'Fresh'를 'New'로 치환):")
df['Description_Replaced'] = df['Description'].str.replace('Fresh', 'New')
display(df['Description_Replaced'])

원본 Description 컬럼:

0        Fresh, Red
1     Sweet, Yellow
2    Organic, Green
3     Citrus, Juicy
4        Ripe, Soft
Name: Description, dtype: object

4-1. `str.split` 예시 (콤마로 Description 분리):

  Desc_Part1 Desc_Part2
0      Fresh        Red
1      Sweet     Yellow
2    Organic      Green
3     Citrus      Juicy
4       Ripe       Soft

4-2. `str.get` 예시 (Description의 첫 번째 분리된 부분):

0      Fresh
1      Sweet
2    Organic
3     Citrus
4       Ripe
Name: Desc_First_Part, dtype: object

4-3. `str.replace()` 예시 (Description에서 'Fresh'를 'New'로 치환):

0          New, Red
1     Sweet, Yellow
2    Organic, Green
3     Citrus, Juicy
4        Ripe, Soft
Name: Description_Replaced, dtype: object

### 5. 문자열 추출 (정규표현식) (String Extract with Regex)

In [ ]:
print("원본 Email 컬럼:")
display(df['Email'])

# str.extract (이메일 주소에서 사용자 이름과 도메인 추출)
print("\n5-1. `str.extract` 예시 (Email에서 사용자 이름과 도메인 추출):")
df[['Username', 'Domain']] = df['Email'].str.extract(r'([^@]+)@(.+)')
display(df[['Email', 'Username', 'Domain']])

원본 Email 컬럼:

0    user1@example.com
1      user2@gmail.com
2    admin@example.com
3    guest@outlook.com
4    support@gmail.com
Name: Email, dtype: object

5-1. `str.extract` 예시 (Email에서 사용자 이름과 도메인 추출):

               Email Username       Domain
0  user1@example.com    user1  example.com
1    user2@gmail.com    user2    gmail.com
2  admin@example.com    admin  example.com
3  guest@outlook.com    guest  outlook.com
4  support@gmail.com  support    gmail.com

### 6. 문자열 검사 (String Contains, StartsWith, EndsWith)

In [ ]:
print("원본 Product 컬럼:")
display(df['Product'])

# str.contains()
print("\n6-1. `str.contains()` 예시 ('Apple'을 포함하는 Product):")
df['Contains_Apple'] = df['Product'].str.contains('Apple')
display(df[['Product', 'Contains_Apple']])

# str.startswith()
print("\n6-2. `str.startswith()` 예시 ('A'로 시작하는 Product):")
df['Starts_With_A'] = df['Product'].str.startswith('A')
display(df[['Product', 'Starts_With_A']])

# str.endswith()
print("\n6-3. `str.endswith()` 예시 ('e'로 끝나는 Product):")
df['Ends_With_e'] = df['Product'].str.endswith('e')
display(df[['Product', 'Ends_With_e']])

원본 Product 컬럼:

0     Apple
1    Banana
2     Apple
3    Orange
4    Banana
Name: Product, dtype: object

6-1. `str.contains()` 예시 ('Apple'을 포함하는 Product):

  Product  Contains_Apple
0   Apple            True
1  Banana           False
2   Apple            True
3  Orange           False
4  Banana           False

6-2. `str.startswith()` 예시 ('A'로 시작하는 Product):

  Product  Starts_With_A
0   Apple           True
1  Banana          False
2   Apple           True
3  Orange          False
4  Banana          False

6-3. `str.endswith()` 예시 ('e'로 끝나는 Product):

  Product  Ends_With_e
0   Apple         True
1  Banana        False
2   Apple         True
3  Orange         True
4  Banana        False

### 7. 문자열 공백 제거 (String Strip)

In [ ]:
# 공백이 있는 샘플 데이터 생성
df_strip_test = pd.DataFrame({'Text': ['  hello world  ', 'python ', '  pandas']})
display(df_strip_test)

# str.strip()
print("\n7-1. `str.strip()` 예시 (양쪽 공백 제거):")
df_strip_test['Text_Strip'] = df_strip_test['Text'].str.strip()
display(df_strip_test['Text_Strip'])

# str.lstrip()
print("\n7-2. `str.lstrip()` 예시 (왼쪽 공백 제거):")
df_strip_test['Text_Lstrip'] = df_strip_test['Text'].str.lstrip()
display(df_strip_test['Text_Lstrip'])

# str.rstrip()
print("\n7-3. `str.rstrip()` 예시 (오른쪽 공백 제거):")
df_strip_test['Text_Rstrip'] = df_strip_test['Text'].str.rstrip()
display(df_strip_test['Text_Rstrip'])

              Text
0    hello world
1          python
2           pandas

7-1. `str.strip()` 예시 (양쪽 공백 제거):

0    hello world
1         python
2         pandas
Name: Text_Strip, dtype: object

7-2. `str.lstrip()` 예시 (왼쪽 공백 제거):

0    hello world
1          python
2           pandas
Name: Text_Lstrip, dtype: object

7-3. `str.rstrip()` 예시 (오른쪽 공백 제거):

0      hello world
1           python
2           pandas
Name: Text_Rstrip, dtype: object

### 8. 날짜 데이터 핸들링 (Date Data Handling)

In [ ]:
print("원본 Date 컬럼 (dtype 확인):")
display(df['Date'].dtype)
display(df['Date'])

# pd.to_datetime (만약 Date 컬럼이 문자열이었다면 변환)
# 현재 df['Date']는 이미 datetime 객체이므로, 문자열 예시를 위해 새로운 컬럼 생성
print("\n8-1. `pd.to_datetime` 예시 (문자열 날짜를 datetime 객체로 변환):")
df['Date_Str'] = ['2023-01-05', '2023/01/06', '01-07-2023', '2023-01-08 10:30:00', '2023-01-09']
df['Date_Converted'] = pd.to_datetime(df['Date_Str'], format='mixed')
# format = mixed로 다양한 형식의 문자열 개별추론
display(df[['Date_Str', 'Date_Converted']])

# dt.strftime (datetime 객체를 특정 형식의 문자열로 변환)
print("\n8-2. `dt.strftime` 예시 (날짜를 'YYYY-MM-DD' 형식의 문자열로 변환):")
df['Date_Formatted'] = df['Date'].dt.strftime('%Y-%m-%d')
display(df[['Date', 'Date_Formatted']])

# pd.to_datetime(format=...) for strptime functionality
# 특정 형식의 문자열 날짜를 datetime으로 변환 (strptime과 유사한 기능)
print("\n8-3. `pd.to_datetime` with `format` 예시 (특정 형식의 문자열 날짜 파싱):")
df['Date_Custom_Str'] = ['01/Jan/2023', '02/Jan/2023', '03/Jan/2023', '04/Jan/2023', '05/Jan/2023']
df['Date_Parsed'] = pd.to_datetime(df['Date_Custom_Str'], format='%d/%b/%Y')
display(df[['Date_Custom_Str', 'Date_Parsed']])

원본 Date 컬럼 (dtype 확인):

dtype('<M8[ns]')

0   2023-01-01
1   2023-01-01
2   2023-01-02
3   2023-01-02
4   2023-01-03
Name: Date, dtype: datetime64[ns]

8-1. `pd.to_datetime` 예시 (문자열 날짜를 datetime 객체로 변환):

              Date_Str      Date_Converted
0           2023-01-05 2023-01-05 00:00:00
1           2023/01/06 2023-01-06 00:00:00
2           01-07-2023 2023-01-07 00:00:00
3  2023-01-08 10:30:00 2023-01-08 10:30:00
4           2023-01-09 2023-01-09 00:00:00

8-2. `dt.strftime` 예시 (날짜를 'YYYY-MM-DD' 형식의 문자열로 변환):

        Date Date_Formatted
0 2023-01-01     2023-01-01
1 2023-01-01     2023-01-01
2 2023-01-02     2023-01-02
3 2023-01-02     2023-01-02
4 2023-01-03     2023-01-03

8-3. `pd.to_datetime` with `format` 예시 (특정 형식의 문자열 날짜 파싱):

  Date_Custom_Str Date_Parsed
0     01/Jan/2023  2023-01-01
1     02/Jan/2023  2023-01-02
2     03/Jan/2023  2023-01-03
3     04/Jan/2023  2023-01-04
4     05/Jan/2023  2023-01-05

In [ ]:
# timedelta (날짜/시간 간격 계산)
print("\n8-4. `pd.Timedelta` 예시 (날짜에 7일 추가):")
seven_days_later = df['Date'] + pd.Timedelta(days=7)
display(seven_days_later)

print("\n8-5. `pd.Timedelta` 예시 (두 날짜 간의 차이 계산):")
date_diff = df['Date_Converted'] - df['Date'] # Date_Converted는 Date_Str에서 변환된 컬럼
display(date_diff)