<a href="https://colab.research.google.com/github/azkq2s/ADP-/blob/main/0_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%95%B8%EB%93%A4%EB%A7%811.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Pandas DataFrame & Series 기초

In [ ]:
#판다스 데이터 구조
#시리즈 / 데이터 프레임
#1차원 / 2차원 배열

#DF 선언 / dic, list, ndarray 등 df화
import pandas as pd
import numpy as np

dataset = np.array([['kor',70], ['math',80]])
df = pd.DataFrame(dataset, columns = ['class', 'score'])
df

#df선언하는 다른 방법
#df = pd.DataFrame([['kor',70],['math',80]], columns=['class', 'score'])
#df = pd.DataFrame({'class': [ 'kor', 'math'],'score'[70,80]})

  class score
0   kor    70
1  math    80

In [ ]:
#시리즈 선언
srs = pd.Series({'idx1':1, 'idx 2': 'a'}, name = 'class')
srs

idx1     1
idx 2    a
Name: class, dtype: object

### 2. 데이터 불러오기 및 저장하기

In [ ]:
#DF를 읽고 저장하기
filepath = 'dataset/data.csv'   #임의의 경로

data = pd.read_csv(filepath, na_values= 'NA', encoding='utf8')

#null을 빈칸이 아닌 어떤 str로 저장된 경우 이를 인식
data.to_csv('result.csv',header=True,index=True,encoding='utf8')

### 3. DataFrame 내용 확인 및 출력 설정

In [ ]:
#df 확인

from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)

#iris       전반적인 내용 확인
iris.head() #앞에 5개 내용 확인
#iris.tail  뒤에 내용 확인

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
#pd.set_option('display.max_columns', None)  #모든 열 출력
#pd.set_option('display.max_row', None)     모든 행 출력 < 이거 하면 큰일남

In [ ]:
#DF 요약 통계정보 확인
display(df.info)
display(df.describe())
# 인포는 데이터 건수와 결측치 수 / describe는 수치형 확인 / EDA시 사용

<bound method DataFrame.info of   class score
0   kor    70
1  math    80>

       class score
count      2     2
unique     2     2
top      kor    70
freq       1     1

In [ ]:
#데이터 프레임은 인덱스 컬럼 속성을 갖고있음
#이들을 수정할 경우 리스트나 np의 array 이용

df.index

RangeIndex(start=0, stop=2, step=1)

### 4. DataFrame 인덱스 조작

In [ ]:
#인덱스 리스트화
list(df.index)

[0, 1]

In [ ]:
#인덱스 변경 (리스트)
df.index = ['A', 'B']
df.index

Index(['A', 'B'], dtype='object')

In [ ]:
#df내의 열을 인덱스로 변경 하는 함수

#df.set_index(keys,drop=True,append=False,inplace=True)

#keys: 인덱스로 사용하고자 하는 컬럼명 str
#drop: 인덱스로 설정한 열 삭제 여부 / append: 기존 인덱스 삭제할지 컬럼으로 추가할지
#inplace: 원본 객체 변경?

df.set_index('class',drop=True,append=False,inplace=True)
df

      score
class
kor      70
math     80

In [ ]:
#df 인덱스를 0부터 시작하는 정수로 변경
df2 = df.reset_index(drop=False, inplace = False)
df2

  class score
0   kor    70
1  math    80

### 5. DataFrame 컬럼 조작

In [ ]:
#df 컬럼명 확인 및 변경

iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
iris.columns = ['sepal length', 'sepal width', 'petal length','petal width']
iris.head()

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
#replace()를 이용하여 컬럼명 내 문자 다른 문자로 변환
iris.columns = iris.columns.str.replace(' ', '_')
iris.head()
#str을 넣어야 컬럼명 글자 하나하나 검사 / 안 넣으면 리스트 원소 한 덩어리가 공백임?으로 생각

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

### 6. 데이터 타입 관리

In [ ]:
# 각 컬럼들의 데이터 타입은 dtype으로 확인 할 수 있다
iris.dtypes

#info도 데이터 타입에 대한 정보가 나온다
#DF 컬럼의 데이터 타입 확인 및 변경
# int / float / bool / datatime / category / object
# object: 복잡형

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
dtype: object

In [ ]:
#데이터 타입 변경
iris['sepal_width'] = iris['sepal_width'].astype('int')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1            3           1.4          0.2
1           4.9            3           1.4          0.2
2           4.7            3           1.3          0.2
3           4.6            3           1.5          0.2
4           5.0            3           1.4          0.2

### 6. df row, col 선택

In [ ]:
#row 선택
#DF[n:m]

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris[1:4]   #1번부터 3번까지의 행 선택

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [ ]:
# 슬라이싱
# s = [1,2,3,4,5]
# s[:-2] = [1,2,3]
# s[:] = [1,2,3,4,5]

In [ ]:
#colum 선택
#DF['컬럼명'] : 하나의 컬럼에 대한 시리즈
#DF[['컬럼명1','컬럼명2']] : 여러 컬럼에 대한 DF

In [ ]:
#row와 col 선택

#DF.iloc[row, col]      #얘는 인덱싱 느낌
#iloc 안에 인수가 하나만 들어갈 시 row로 인식

#iris.iloc[1:4]
iris.iloc[[1,3,4], 2:4] #1,3,4행 2,3열

   petal length (cm)  petal width (cm)
1                1.4               0.2
3                1.5               0.2
4                1.4               0.2

In [ ]:
#DF.loc[row,col]    #여기는 인덱승 느낌은 아니고 이름으로 ? 하는듯
#iris.loc[1:3]      1,2,3 행
iris.loc[[1,3,4],'sepal width (cm)':'petal width (cm)']

   sepal width (cm)  petal length (cm)  petal width (cm)
1               3.0                1.4               0.2
3               3.1                1.5               0.2
4               3.6                1.4               0.2

### 6. 데이터프레임 값 변경 및 추가

In [ ]:
#선택한 값 변경 # 주로 이상치 값 변경
import pandas as pd

# 임의의 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney'],
    'Score': [85, 92, 78, 88, 95]
}
my_df = pd.DataFrame(data)
my_df.loc[3, 'Score'] = 30
my_df['Age'] = my_df['Age']  + 10
my_df

      Name  Age      City  Score
0    Alice   35  New York     85
1      Bob   40     Paris     92
2  Charlie   45    London     78
3    David   50     Tokyo     30
4      Eve   55    Sydney     95

In [ ]:
import pandas as pd

# 임의의 데이터프레임 생성
my_df = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
    'City': ['New York', 'Paris']
})

new_row = pd.Series({
    'Name': 'Charlie',
    'Age': 35,
    'City': 'London'
})

# pd.concat()을 사용하여 행 추가
# ignore_index=True를 사용하여 인덱스를 재설정합니다.
# pd.concat()은 원본 DataFrame을 변경하지 않고 새로운 DataFrame을 반환합니다.
my_df_appended = pd.concat([my_df, new_row.to_frame().T], ignore_index=True)

print("DataFrame after appending new row (using pd.concat):")
display(my_df_appended)

#append 사용시      df.append는 pandas 1.4.0버전부터 사용 x
#my_df = mt_df.append(new_row)

DataFrame after appending new row (using pd.concat):

      Name Age      City
0    Alice  25  New York
1      Bob  30     Paris
2  Charlie  35    London

In [ ]:
#col 추가
new_column_values = ['Male', 'Female']

# my_df에 'Gender'라는 이름의 새 컬럼 추가
my_df['Gender'] = new_column_values

print("Gender 컬럼이 추가된 my_df:")
display(my_df)

Gender 컬럼이 추가된 my_df:

    Name  Age      City  Gender
0  Alice   25  New York    Male
1    Bob   30     Paris  Female

In [ ]:
#삭제
#DF.drop(index=None, columns = None, inplace = False)
my_df_appended.drop(0, inplace=True)
my_df_appended.drop(columns= 'City',inplace=True)
my_df_appended
#inplace=True 잘 안 씀

      Name Age
1      Bob  30
2  Charlie  35